"""
===============================================================================
Import ForexFactory CSV → news_calendar.json
===============================================================================
แปลง CSV export จาก ForexFactory Calendar เป็น news_calendar.json

วิธีใช้:
  1. เข้า https://www.forexfactory.com/calendar
  2. Filter: Impact = High only, Currencies = เลือกทั้งหมดที่บอทใช้
  3. เลือกสัปดาห์ที่ต้องการ → กด Export (ล่างขวา) → ดาวน์โหลด CSV
  4. รัน: python scripts/import_forexfactory_csv.py path/to/calendar.csv

ForexFactory CSV format (ณ 2026):
  Title,Country,Date,Time,Impact,Forecast,Previous,URL

ผลลัพธ์: เขียน config/news_calendar.json ใหม่
===============================================================================
"""

import argparse
import json
import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

# Add project root to path
_THIS_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _THIS_DIR.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from config.news_csv_parser import parse_forexfactory_csv


def main():
    parser = argparse.ArgumentParser(description="Import ForexFactory CSV → news_calendar.json")
    parser.add_argument("csv_path", help="Path to ForexFactory CSV")
    parser.add_argument("--tz-offset", type=float, default=0.0,
                        help="Timezone offset ของ CSV (เทียบ UTC) default=0")
    parser.add_argument("--valid-days", type=int, default=7,
                        help="จำนวนวันที่ไฟล์ valid (default=7)")
    parser.add_argument("--output", default=None,
                        help="Path to output JSON (default: config/news_calendar.json)")
    args = parser.parse_args()

    csv_path = Path(args.csv_path)
    if not csv_path.exists():
        print(f"❌ ไม่พบไฟล์: {csv_path}")
        sys.exit(1)

    output_path = Path(args.output) if args.output else (
        Path(__file__).resolve().parent.parent / "config" / "news_calendar.json"
    )

    events = parse_forexfactory_csv(csv_path, source_tz_offset_hours=args.tz_offset)

    if not events:
        print("❌ ไม่มี high-impact events — ยกเลิก")
        sys.exit(1)

    now = datetime.now(timezone.utc).replace(microsecond=0)
    valid_until = now + timedelta(days=args.valid_days)

    out = {
        "_comment": "Generated by scripts/import_forexfactory_csv.py",
        "updated_at": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "valid_until": valid_until.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "events": sorted(events, key=lambda e: e["datetime_utc"]),
    }

    os.makedirs(output_path.parent, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)

    print(f"✅ เขียน {output_path} เรียบร้อย ({len(events)} events, valid ถึง {valid_until.date()})")


if __name__ == "__main__":
    main()
